### ISSUE TITLE
Cursor being put in wrong position

### ISSUE THREAD

**Issue by ghost** [dbalatero/VimMode.spoon#57] opened 2020-09-09 14:09 UTC

**Comment by assertcarlos** [comment] 2020-09-09 14:13
The cursor is being put after the letter rather than before it. This behaviour only seems to happen when I clone a project.

**Comment by dbalatero** [comment] 2020-09-09 14:27
@assertcarlos Which flavor of normal mode is running?

https://github.com/dbalatero/VimMode.spoon#flavors-of-vimmode

You can tell by the popup box (bad UI I know, I need to figure out something for this)

Advanced mode has no asterisk:
![image](https://user-images.githubusercontent.com/59429/92611684-08c73080-f287-11ea-8ea1-ec91083932d7.png)

Fallback mode has an asterisk and often is at the bottom of the screen
![image](https://user-images.githubusercontent.com/59429/92611743-1b416a00-f287-11ea-94c4-c23f64525532.png)

**Comment by assertcarlos** [comment] 2020-09-09 15:00
Hi @dbalatero Just checked and i'm using Advanced mode without the asterisk.

**Comment by dbalatero** [comment] 2020-09-09 16:25
Ok sounds good!

> This behaviour only seems to happen when I clone a project.

I don't understand what this means?

**Comment by assertcarlos** [comment] 2020-09-09 18:26
When I create a new project in Xcode it works how you would expect but when I clone a repo that is when it places the cursor in the wrong position.

I can close Xcode and open the cloned project again and the problem persists but as soon as I open a project which isn't cloned the problem disappears. It's very strange.

**Comment by dbalatero** [comment] 2020-09-09 18:46
I don't use Xcode. I think I need you to write up exact repro steps with screenshots or I probably can't track down or fix this issue. Include the exact repo you cloned as well, as long as it's public. Thanks!

**Comment by assertcarlos** [comment] 2020-09-09 19:12
I don't know what kind of screenshots which would convey what i'm experiencing but as an example [this](https://github.com/appbrewery/Clima-iOS13) repo would reproduce the issue if you were able to clone it and open it in XCode.

Is there anything I can do to try and debug this to the console?

**Comment by dbalatero** [comment] 2020-09-09 22:06
If you can explain in detail, that would be great.

* Open XCode
* Go to the File Menu, select Blah
* Paste in a URL
* Hit enter

etc? Put yourself in my shoes as someone getting a bug report who has barely used XCode and isn't sure if there is a particular path down the UI that you might be taking. That way I won't waste a bunch of time guessing, or kick it back to you with "can't reproduce, won't fix"

**Comment by dbalatero** [comment] 2020-09-09 22:06
For example, I don't even know when you enter Vim normal mode, or what field you're in.

**Comment by assertcarlos** [comment] 2020-09-10 06:42
Sorry i'll try and explain it better 

1. Open XCode and select "Clone an existing project"
2. Enter the repository url and hit clone
3. <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd> and open `WeatherViewController`
4. From there go to any line and while in normal mode and try using `f<char>` or by moving forward a word using `w`

That will reproduce the weird bug i'm seeing

**Comment by yoricfr** [comment] 2020-10-24 11:06
Hey, I'm joining the discussion.
I noticed a bug positioning the cursor with a shift (a few extra characters before / after where it's supposed to be).
It can happens for example when jumping words forward/backward, or when performing a `f` search.

In my case, it happens whenever my text contains UTF8 characters encoded on more than one byte.
For example, it's working as expected on this text:
`"It's like being on a ship," Sam said: "Surf with it, don't fight it."`
But not on this line of text:
`“It's like being on a ship,” Sam said: “Surf with it, don't fight it.”`
The subtle difference lies in the smart quotes (TextEdit insert them by default). The same behavior happens when text contains accents (éñò...) or some non-english characters from other alphabets (ÆПИ...).
Those characters are encoded with more than one byte, and aren't handled correctly with default Lua string's functions, such as `sub()`, `len()` and `find()`.

Specifically, if you feed `string.len()` with the `“` parameter (smart double quote), you get 3, not 1. Hence resulting a 2-extra character shift in the cursor position.

Hammerspoon and Lua 5.3 comes with [a basic utf8 library](https://q-syshelp.qsc.com/Content/Control_Scripting/Lua_5.3_Reference_Manual/Standard_Libraries/4_-_Basic_UTF-8_Support.htm) offering the following functions:

- utf8.char()
- utf8.charpattern()
- utf8.codes()
- utf8.codepoint()
- utf8.len()
- utf8.offset()

The `string.sub()` function can be replaced with the following (code taken from [Stackoverflow](https://stackoverflow.com/questions/43138867/lua-unicode-using-string-sub-with-two-byted-chars))

```
function utf8.sub(s,i,j)
    i=utf8.offset(s,i)
    j=utf8.offset(s,j+1)-1
    return string.sub(s,i,j)
end
```

I didn't find the code equivalent for `string.find()`, but I guess replacing all those string functions to their "UTF8" counterpart would solve the issue. (it actually does on my implementation)

By the way, thanks @dbalatero for this fabulous VimMode Spoon. It's really super awesome to get those advanced features from almost any text area. The `f` and `t` search specifically blew my mind, as it's very "vim-like".
I didn't know it was possible to get those "smart" moves from anywhere on the Mac. I heavily got inspired by your code and implemented "sentence" motions, to jump a sentence forward/backward. Sentence delimiters being `.` or `?` or `!`.

**Comment by dbalatero** [comment] 2020-10-24 16:27
Yeah it's definitely UTF-8. I notice this for example in Messages.app, when OSX converts an apostrophe to a curly one, which changes my offsets by 2 chars due to the extra bytes.

I did try to fix UTF8 before but didn't have great luck with it. I know the Lua version changed recently, and I'm trying to figure out if it just changed to 5.3 or to 5.4? Hammerspoon frustratingly is stuck in the past in some ways - I can't find a changelog describing it, no semantic versioning (their recent patch point upgrades broke everything in this lib and my config), and I can't figure out how to actually use the Spoon package manager as a library maintainer.

In any case, I will try these utf8 functions.

> I heavily got inspired by your code and implemented some "sentence" motions, to jump a sentence forward/backward. Sentence delimiters being . or ? or !.

Is this a PR you have for this repo?

**Comment by dbalatero** [comment] 2020-10-25 21:28
Opening a new branch/PR to explore this.

**Comment by dbalatero** [comment] 2020-10-25 22:58
@yoricfr Would you pull this development branch and help me test it out? I dropped in luautf8 as a vendored library, and replaced all `string.*()` calls with the utf8 equivalent.

https://github.com/dbalatero/VimMode.spoon/pull/62

**Comment by yoricfr** [comment] 2020-10-27 17:04
Thanks @dbalatero for creating the utf8 branch and let me test it. I will post the results directly to the PR.

About hopping through sentences, I don't have any branch to show. It was a request from a writer editing novels. It's still experimental.
As it's not a vim feature, I guess it's not really meant to be implemented here.
Here is a short screencast.

![Screencast](https://i.postimg.cc/Dz5s2TWV/One.gif)

**Comment by dbalatero** [comment] 2020-10-27 17:49
`:help sentence`

```
5. Text object motions					*object-motions*

							*(*
(			[count] |sentence|s backward.  |exclusive| motion.

							*)*
)			[count] |sentence|s forward.  |exclusive| motion.

							*{*
{			[count] |paragraph|s backward.  |exclusive| motion.

							*}*
}			[count] |paragraph|s forward.  |exclusive| motion.
```

and

```
							*sentence*
A sentence is defined as ending at a '.', '!' or '?' followed by either the
end of a line, or by a space or tab.  Any number of closing ')', ']', '"'
and ''' characters may appear after the '.', '!' or '?' before the spaces,
tabs or end of line.  A paragraph and section boundary is also a sentence
boundary.
If the 'J' flag is present in 'cpoptions', at least two spaces have to
follow the punctuation mark; <Tab>s are not recognized as white space.
The definition of a sentence cannot be changed.
```

Looks like there _is_ a sentence motion of sorts. It totally sucks in a code file though! But for plain text it seems to work well.

**Comment by yoricfr** [comment] 2020-10-27 19:10
Oh! You're totally right, I missed that!
The great Vim grammar understands sentences.
This surely is not for coders but for writers.

**Closed** 2020-11-04 21:42 UTC
